---
- name: Create Kafka group
  group: name=kafka state=present

- name: Create Kafka user
  user: name=kafka shell=/bin/bash home=/home/kafka group=kafka

- name: Add Kafka user to group 'confluent'
  user:
    name: kafka
    groups: confluent
    append: yes

- name: Create kafka utils directory
  file: path={{ kafka_utils_dir }} state=directory owner=kafka group=kafka mode=0660

- name: Template cluster_type.yaml to contain cluster info
  template: src=cluster_type.j2 dest={{ kafka_utils_dir }}/cluster_type.yaml owner=kafka group=kafka mode=0660

- name: Backup original server.properties
  command: "cp {{ kafka_config_dir }}/server.properties {{ kafka_config_dir }}/server.properties.{{ confluent_platform_package_version }} creates={{ kafka_config_dir }}/server.properties.{{ confluent_platform_package_version }}"

- name: Template kafka server.properties
  template: src=server.j2 dest=/etc/kafka/server.properties owner=kafka group=kafka mode=0664

- name: Create alternate storage directory
  file: "path={{ alternate_storage_dir }} state=directory owner=kafka group=kafka mode=0775"
  when: use_storage_symlink is defined

- name: Create /var/lib/kafka to /ephmemeral/kafka symlink
  file: "src={{ alternate_storage_dir }} dest=/var/lib/kafka state=link"
  when: use_storage_symlink is defined

- name: Kafka broker config ownership check
  file: "path=/etc/{{ item }} state=directory owner=kafka group=kafka recurse=yes mode=0774"
  with_items:
    - kafka
    - kafka-connect-elasticsearch
    - kafka-connect-hdfs
    - kafka-connect-jdbc
    - kafka-rest

- name: Kafka logs ownership check
  file: path=/var/log/kafka state=directory owner=kafka group=kafka mode=0775

- name: Copy Kafka broker systemd service config
  copy: src=kafka.service dest=/lib/systemd/system/kafka.service owner=root group=root mode=0644

- name: Set Kafka broker to autostart via systemd
  systemd:
    name: kafka
    enabled: yes
    masked: no

- name: Change Kafka directory permissions
  file:
    path: /var/lib/kafka
    mode: '0770'

- name: Restart Kafka
  systemd:
    name: kafka
    state: restarted

- name: Wait for Kafka broker startup
  wait_for: path=/var/log/syslog search_regex="started \(kafka.server.KafkaServer\)" timeout=300
